[build]
target = "riscv64gc-unknown-none-elf"
# target = "loongarch64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tos/src/linker.ld", "-Cforce-frame-pointers=yes"
]

runner = "./qemu-run.sh"

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tos/src/loongarch_linker.ld", "-Cforce-frame-pointers=yes"
]

runner = "./qemu-loongarch-run.sh"

[net]
retry = 3
